### ISSUE TITLE
ntpUpdate procedure

### ISSUE THREAD

**Issue by danistrigaro** [HarithKK/ISTSOS#6]
Why do you use the ntpUpdate function every time you get a measure?
Maybe it is better in this way:

`
uint32_t* timepointer=istsos.ntpUpdate("metasntp11.admin.ch", 0);
rtc.adjust(DateTime((uint16_t) timepointer[0], (uint8_t) timepointer[1], (uint8_t) timepointer[2], (uint8_t) timepointer[3], (uint8_t) timepointer[4], (uint8_t) timepointer[5]));
`

You can firstly use this code in the setup() and then only to re-sync the RTC maybe once per day or once per week.

**Comment by kolithawarnakulasooriya** [comment]
8ce413bbc7c2ac7d28a34812ac51a1d0b8ce6612 Done
